### ISSUE TITLE
[Feature Request] Wake from light sleep restarts the USB driver?

### ISSUE THREAD

**Issue by thundercatsNZ** [ryodeushii/gem80-qmk-firmware#10]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Hi, this is fantastic work, you've really improved the functionality of these boards. Thanks!

I'm not sure if this is part of your update, but I can see a call to restart the usb driver from exit_light_sleep() in mcu_pwr.c

`    if (dev_info.link_mode == LINK_USB) {
        usb_lld_wakeup_host(&USB_DRIVER);
        restart_usb_driver(&USB_DRIVER);
    }`

Is this to fix some problem behaviour? Having the keyboard disconnecting from the device all the time is causing me some issues, and enter_light_sleep just turns off the leds, right? Could I recompile with this block removed with no ill effects?

Thanks again for your work.

**Comment by ryodeushii** [comment]
Hi. If you happen to have powered USB hub or KVM switch with keyboard connected to it then it's crucial to have statement you mentioned to be enabled. 
If you don't have KVM and/or powered USB hub or your PC doesn't keep USB ports powered on it should be safe for you to remove these lines. 
Anyway you can remove these lines and recompile. The worst thing - you'd have to reflash with prebuild version if something is not working

**Comment by thundercatsNZ** [comment]
Ok cool, thanks for the explanation!
