### ISSUE TITLE
[Feature Request] [Question] Is the Field75 (HE) supported in any way?

### ISSUE THREAD

**Issue by wtrflsh** [ryodeushii/gem80-qmk-firmware#18]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

**Comment by ryodeushii** [comment]
Hello, unforunately neither of Field versions (V1 and HE) are supported, they are built on custom firmwares (non-QMK) so it is what it is.
