### ISSUE TITLE
[Bug] NuPhy Halo75 v2 on bluetooth waking from sleep - missed inputs

### ISSUE THREAD

**Issue by jborbik** [ryodeushii/gem80-qmk-firmware#20]
### Describe the Bug

Currently when the NuPhy Halo75 v2 with v1.1.4 firmware wakes up on bluetooth from sleep it misses inputs. This is not the case with the stock firmware if the keyboard wakes up from shallow sleep (between 5 and 30 minutes of inactivity). Is there a way to fix that?

### Keyboard Used

NuPhy Halo75 v2

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [X] Karabiner (macOS)

**Comment by ryodeushii** [comment]
Hi. Unfortunately this is trade-off to make keyboard wake properly udner all circumstances (in any mode with or without cable attached). Especially it's true when keyboard is being woke up during attempt to enter BIOS or when you rely on usage of externally-powered USB hubs and / or KVM switches

**Comment by jborbik** [comment]
I see, thank you for the answer!
